version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: dockerfile.app
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - auth_service
  auth_service:
    build:
      context: .
      dockerfile: dockerfile.auth
    ports:
      - "50051:50051"
